[package]
name = "newton-hypervisor"
version = "0.0.1"
edition = "2021"
license = "GPL-2.0-or-later"
description = "Bare-metal hypervisor for running Newton 2.x ROMs natively on Cortex-A53 Raspberry Pi."

[[bin]]
name = "newton-hypervisor"
path = "src/main.rs"

[profile.dev]
panic = "abort"
opt-level = 1
debug = 2

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
debug = 2
strip = false
